### ISSUE TITLE
check_updates reports security updates needed incorrectly

### ISSUE THREAD

**Issue by philrumble** [matteocorti/check_updates#30]
Running on CentOS Linux release 7.7.1908 (Core)

check_update reports security updates needed when , in fact none are needed.

```
/usr/lib64/nagios/plugins/check_updates --clean -w 75 -c 150 -t 30 -vvv
[extra-opts] check_updates --clean -w 75 -c 150 -t 30 -vvv
Searching for DNF or YUM in /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
Executing 'which dnf'
which: no dnf in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
Executing 'which yum'
/usr/bin/yum
Checking a linux system
Running on CentOS Linux release 7.7.1908 (Core)
Using Yum or DNF
running a Linux kernel: 3.10.0-1062.12.1
kernel: running = 3.10.0-1062.12.1, installed = 3.10.0-1062.12.1
Checking if YUM/DNF supports the --security option
Using YUM: security plugin installed
Cleaning YUM/DNF cachesSecurity updates available
CHECK_UPDATES CRITICAL - 2 security updates and 1 non-security update available | total_updates=3;75;150 security_updates=2;75;150
Repository (security)
Repository (security)
python-urllib3.noarch
```

using yum

```
sudo yum check-updates --security --quiet
Repository extras is listed more than once in the configuration
Repository updates is listed more than once in the configuration
```

**Comment by matteocorti** [comment]
Could you please run the plugin again with the `-d` (debug) option and post the result?

**Comment by jehane** [comment]
I have a similar issue. (Centos 7.7.1908 up-to-date) 

[root@server ~]# LANG=C /usr/lib64/nagios/plugins/check_updates -d
[DBG] Updater: yum
[DBG] Running "/usr/bin/yum check-update --assumeno -q  2>&1"
[DBG] Repository 'puppet5' is missing name in configuration, using id
[DBG] Running "/usr/bin/yum check-update --assumeno -q  --security 2>&1 2>&1"
[DBG] Repository 'puppet5' is missing name in configuration, using id
CHECK_UPDATES CRITICAL - 1 security update available | total_updates=1;0;0 security_updates=1;0;0
Repository (security)

If I add a name in the repo config file, no more false positive

**Comment by matteocorti** [comment]
This could be indeed the problem. I have to parse the output of YUM/DNF and it can be that I miss something.

**Comment by matteocorti** [comment]
I just committed a new version. Could you please checkt it out and test it?

**Comment by jehane** [comment]
It's not working for me (either in french or by forcing output in english) 
[root@server ~]# LANG=C ./check_updates -d
[DBG] Updater: yum
[DBG] Running "/usr/bin/yum check-update --assumeno -q  2>&1"
[DBG] Repository 'puppet5' is missing name in configuration, using id
[DBG] Running "/usr/bin/yum check-update --assumeno -q  --security 2>&1 2>&1"
[DBG] Repository 'puppet5' is missing name in configuration, using id
CHECK_UPDATES CRITICAL - 1 security update available | total_updates=1;0;0 security_updates=1;0;0
Repository (security)
[root@server ~]# ./check_updates -d
[DBG] Updater: yum
[DBG] Running "/usr/bin/yum check-update --assumeno -q  2>&1"
[DBG] Il manque le nom du dépôt 'puppet5' dans la configuration, utilisation de l'identifiant
[DBG] Running "/usr/bin/yum check-update --assumeno -q  --security 2>&1 2>&1"
[DBG] Il manque le nom du dépôt 'puppet5' dans la configuration, utilisation de l'identifiant
CHECK_UPDATES CRITICAL - 1 security update available | total_updates=1;0;0 security_updates=1;0;0
Il (security)

However, I just found that yum got an option to disable all error warnings by adding  -e 0 to the command line. It make the warning about the repo name go away (and I assume the duplicate the orignal reporter have too). 

[root@server ~]# LANG=C yum update -q
Repository 'puppet5' is missing name in configuration, using id
[root@server ~]# LANG=C yum update -q -e0
[root@server ~]#

**Comment by matteocorti** [comment]
Thanks for the suggestion. Can you please test the last commit?

**Comment by jehane** [comment]
Works for me 
[root@server ~]# ./check_updates 
CHECK_UPDATES OK - no updates available | total_updates=0;0;0 security_updates=0;0;0

**Comment by matteocorti** [comment]
Fixed in 1.7.9

**Comment by matteocorti** [comment]
Even in French?

**Comment by jehane** [comment]
Even in French (I didn't test in other languages)

**Comment by philrumble** [comment]
I've tested this and it works, do you know when this will be available in the epel repo?

**Comment by matteocorti** [comment]
I don’t know. You should open an issue there and ask to update the package.

**Comment by mhjacks** [comment]
I see the bug and I will work on getting an update published.  Thanks for the bug report!

**Comment by matthewgeier** [comment]
It still does it for me. Seems related - as running as non-root an error is returned about 'spacewalk' (we use a satellite server for updates)

-bash-4.2$ /usr/lib/nagios/plugins/contrib/check_updates -v -w 5 -c 10 -t 30 -d
[DBG] check_updates version: 1.7.11
[DBG] system info:           Linux rosaceae.acfr.usyd.edu.au 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG]                        NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"
Checking a linux system
Running on Red Hat Enterprise Linux Server release 7.8 (Maipo)
[DBG] Updater: yum
Using Yum or DNF
running a Linux kernel: 3.10.0-1127.10.1
kernel: running = 3.10.0-1127.10.1, installed = 3.10.0-1127.10.1
[DBG] Running "/bin/yum check-update --assumeno --errorlevel=0 -q  2>&1"
[DBG] *Note* Spacewalk repositories are not listed below. You must run this command as root to access Spacewalk repositories.
[DBG] Running "/bin/yum check-update --assumeno --errorlevel=0 -q  --security 2>&1 2>&1"
[DBG] *Note* Spacewalk repositories are not listed below. You must run this command as root to access Spacewalk repositories.
CHECK_UPDATES CRITICAL - 1 security update available | total_updates=1;5;10 security_updates=1;5;10
*Note* (security)

-

Of course, running the program as root, works fine. But nrpe execs this as the nagios sandbox user.

**Comment by matteocorti** [comment]
It's an other problem (but similar)

**Comment by abeerens** [comment]
Unfortunately the problem still exists in 7.13

[beheer@server ~]$ /usr/local/ncpa/plugins/check_updates -t 60

CHECK_UPDATES CRITICAL - 2 security updates available | total_updates=2;0;0 security_updates=2;0;0
2021-02-01 (security)
2021-02-01 (security)


[beheer@server ~]$ sudo /usr/local/ncpa/plugins/check_updates -t 60

CHECK_UPDATES OK - no updates available | total_updates=0;0;0 security_updates=0;0;0


[beheer@server ~]$ sudo yum upgrade

Updating Subscription Management repositories.
Last metadata expiration check: 0:13:59 ago on Mon 01 Feb 2021 12:01:30 PM CET.
Dependencies resolved.
Nothing to do.
Complete!


Regards,
Antoine Beerens
Conclusion-Xforce

**Comment by matteocorti** [comment]
Can you please execute the plugin with `-d` and post the output?

**Comment by abeerens** [comment]
Already on it:
[beheer@server ~]$ /usr/local/ncpa/plugins/check_updates -t 60 -d
[DBG] check_updates version: 1.7.13
[DBG] system info:           Linux server.nl 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Wed Dec 16 03:30:52 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
[DBG]                        NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"
[DBG] Updater: yum
[DBG] Running "/usr/bin/dnf check-update --assumeno --errorlevel=0 -q  2>&1"
[DBG] 2021-02-01 12:18:53,032 [ERROR] dnf:2279:MainThread @logutil.py:194 - [Errno 13] Permission denied: '/var/log/rhsm/rhsm.log' - Further logging output will be written to stderr
[DBG] 2021-02-01 12:18:53,043 [ERROR] dnf:2279:MainThread @identity.py:156 - Reload of consumer identity cert /etc/pki/consumer/cert.pem raised an exception with msg: [Errno 13] Permission denied: '/etc/pki/consumer/key.pem'
[DBG] Running "/usr/bin/dnf check-update --assumeno --errorlevel=0 -q  --security 2>&1 2>&1"
[DBG] 2021-02-01 12:18:56,794 [ERROR] dnf:2282:MainThread @logutil.py:194 - [Errno 13] Permission denied: '/var/log/rhsm/rhsm.log' - Further logging output will be written to stderr
[DBG] 2021-02-01 12:18:56,804 [ERROR] dnf:2282:MainThread @identity.py:156 - Reload of consumer identity cert /etc/pki/consumer/cert.pem raised an exception with msg: [Errno 13] Permission denied: '/etc/pki/consumer/key.pem'
CHECK_UPDATES CRITICAL - 2 security updates available | total_updates=2;0;0 security_updates=2;0;0
2021-02-01 (security)
2021-02-01 (security)


Problem can be fixed by changing the rights on the file /var/log/rhsm/rhsm.log

regards,
Antoine

**Comment by matteocorti** [comment]
It seems that `dnf check-update` is not able to access `/var/log/rhsm/rhsm.log`. See the errors in the log.

I could try to catch the error message, but the issue is not in the plugin
